In [19]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from datetime import datetime

In [3]:
#!pip install selenium

In [4]:
# set 100 Thailand
url = 'https://www.set.or.th/th/market/index/set100/overview'

In [5]:
driver = webdriver.Chrome(r"C:\Users\kwach\python\Web Scraping\chromedriver.exe")
driver

C:\Users\kwach\AppData\Local\Temp\ipykernel_31396\1495227948.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\kwach\python\Web Scraping\chromedriver.exe")

In [6]:
driver.get(url)

In [7]:
data = driver.page_source

In [9]:
df = pd.read_html(data)[1]

In [10]:
df.columns

Index(['หลักทรัพย์  (Click to sort Ascending)',
       'เปิด  (Click to sort Ascending)', 'สูงสุด  (Click to sort Ascending)',
       'ต่ำสุด  (Click to sort Ascending)',
       'ล่าสุด  (Click to sort Ascending)',
       'เปลี่ยนแปลง  (Click to sort Ascending)',
       '% เปลี่ยนแปลง  (Click to sort Ascending)',
       'เสนอซื้อ  (Click to sort Ascending)',
       'เสนอขาย  (Click to sort Ascending)',
       'ปริมาณ (หุ้น)  (Click to sort Ascending)',
       'มูลค่า ('000 บาท)  (Click to sort Ascending)'],
      dtype='object')

In [11]:
# set columns name
columns_name = []
for c in df.columns:
    columns_name.append(c.replace('  (Click to sort Ascending)',''))

In [12]:
columns_name

['หลักทรัพย์',
 'เปิด',
 'สูงสุด',
 'ต่ำสุด',
 'ล่าสุด',
 'เปลี่ยนแปลง',
 '% เปลี่ยนแปลง',
 'เสนอซื้อ',
 'เสนอขาย',
 'ปริมาณ (หุ้น)',
 "มูลค่า ('000 บาท)"]

In [13]:
df.columns = columns_name

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   หลักทรัพย์         100 non-null    object
 1   เปิด               100 non-null    float64
 2   สูงสุด             100 non-null    float64
 3   ต่ำสุด             100 non-null    float64
 4   ล่าสุด             100 non-null    float64
 5   เปลี่ยนแปลง        100 non-null    float64
 6   % เปลี่ยนแปลง      100 non-null    float64
 7   เสนอซื้อ           100 non-null    float64
 8   เสนอขาย            100 non-null    float64
 9   ปริมาณ (หุ้น)      100 non-null    int64
 10  มูลค่า ('000 บาท)  100 non-null    float64
dtypes: float64(9), int64(1), object(1)
memory usage: 8.7+ KB

In [15]:
df.head()

,หลักทรัพย์,เปิด,สูงสุด,ต่ำสุด,ล่าสุด,เปลี่ยนแปลง,% เปลี่ยนแปลง,เสนอซื้อ,เสนอขาย,ปริมาณ (หุ้น),มูลค่า ('000 บาท)
0,AAV,2.86,2.92,2.82,2.90,0.04,1.40,2.90,2.92,60050907,172827.08
1,ACE,1.96,1.96,1.92,1.92,-0.02,-1.03,1.92,1.93,11239501,21884.11
2,ADVANC,214.00,214.00,211.00,213.00,1.00,0.47,213.00,214.00,3393631,721870.25
3,AMATA,22.80,22.90,22.50,22.60,-0.20,-0.88,22.50,22.60,2915485,65961.38
4,AOT,70.00,70.50,69.75,70.50,-0.25,-0.35,70.25,70.50,10029657,704023.14

In [16]:
# set index
df.set_index('หลักทรัพย์', inplace=True)

In [17]:
df

,เปิด,สูงสุด,ต่ำสุด,ล่าสุด,เปลี่ยนแปลง,% เปลี่ยนแปลง,เสนอซื้อ,เสนอขาย,ปริมาณ (หุ้น),มูลค่า ('000 บาท)
หลักทรัพย์,,,,,,,,,,
AAV,2.86,2.92,2.82,2.90,0.04,1.40,2.90,2.92,60050907,172827.08
ACE,1.96,1.96,1.92,1.92,-0.02,-1.03,1.92,1.93,11239501,21884.11
ADVANC,214.00,214.00,211.00,213.00,1.00,0.47,213.00,214.00,3393631,721870.25
AMATA,22.80,22.90,22.50,22.60,-0.20,-0.88,22.50,22.60,2915485,65961.38
AOT,70.00,70.50,69.75,70.50,-0.25,-0.35,70.25,70.50,10029657,704023.14
...,...,...,...,...,...,...,...,...,...,...
TRUE,6.65,6.65,6.50,6.60,0.00,0.00,6.55,6.60,22729188,149078.53
TTB,1.67,1.67,1.63,1.66,-0.01,-0.60,1.65,1.66,560184527,923361.22
TU,14.40,14.50,13.70,13.70,-0.70,-4.86,13.70,13.80,41233041,573309.24
VGI,3.14,3.16,3.10,3.14,0.02,0.64,3.12,3.14,353448693,1106312.59
WHA,4.50,4.50,4.42,4.46,-0.02,-0.45,4.44,4.46,18352654,81821.78

In [20]:
df['Timestamp'] = datetime.now().strftime("%Y-%m-%d")

In [21]:
df

,เปิด,สูงสุด,ต่ำสุด,ล่าสุด,เปลี่ยนแปลง,% เปลี่ยนแปลง,เสนอซื้อ,เสนอขาย,ปริมาณ (หุ้น),มูลค่า ('000 บาท),Timestamp
หลักทรัพย์,,,,,,,,,,,
AAV,2.86,2.92,2.82,2.90,0.04,1.40,2.90,2.92,60050907,172827.08,2023-06-06
ACE,1.96,1.96,1.92,1.92,-0.02,-1.03,1.92,1.93,11239501,21884.11,2023-06-06
ADVANC,214.00,214.00,211.00,213.00,1.00,0.47,213.00,214.00,3393631,721870.25,2023-06-06
AMATA,22.80,22.90,22.50,22.60,-0.20,-0.88,22.50,22.60,2915485,65961.38,2023-06-06
AOT,70.00,70.50,69.75,70.50,-0.25,-0.35,70.25,70.50,10029657,704023.14,2023-06-06
...,...,...,...,...,...,...,...,...,...,...,...
TRUE,6.65,6.65,6.50,6.60,0.00,0.00,6.55,6.60,22729188,149078.53,2023-06-06
TTB,1.67,1.67,1.63,1.66,-0.01,-0.60,1.65,1.66,560184527,923361.22,2023-06-06
TU,14.40,14.50,13.70,13.70,-0.70,-4.86,13.70,13.80,41233041,573309.24,2023-06-06
VGI,3.14,3.16,3.10,3.14,0.02,0.64,3.12,3.14,353448693,1106312.59,2023-06-06
WHA,4.50,4.50,4.42,4.46,-0.02,-0.45,4.44,4.46,18352654,81821.78,2023-06-06

In [22]:
df.to_csv('set100.csv')